import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF006E14),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF88FC7F),
  secondary: Color(0xFF0E6D35),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFF9FF6AF),
  onSecondaryContainer: Color(0xFF00210B),
  tertiary: Color(0xFF38656A),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFBCEBF0),
  onTertiaryContainer: Color(0xFF002022),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFCFDF6),
  onBackground: Color(0xFF1A1C19),
  surface: Color(0xFFFCFDF6),
  onSurface: Color(0xFF1A1C19),
  surfaceVariant: Color(0xFFDEE4D8),
  onSurfaceVariant: Color(0xFF42493F),
  outline: Color(0xFF73796F),
  onInverseSurface: Color(0xFFF1F1EB),
  inverseSurface: Color(0xFF2F312D),
  inversePrimary: Color(0xFF6CDF66),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF006E14),
  outlineVariant: Color(0xFFC2C8BC),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF6CDF66),
  onPrimary: Color(0xFF003906),
  primaryContainer: Color(0xFF00530D),
  onPrimaryContainer: Color(0xff46B946),
  secondary: Color(0xFF83D995),
  onSecondary: Color(0xFF003917),
  secondaryContainer: Color(0xFF005225),
  onSecondaryContainer: Color(0xFF9FF6AF),
  tertiary: Color(0xFFA0CFD3),
  onTertiary: Color(0xFF00363A),
  tertiaryContainer: Color(0xFF1E4D51),
  onTertiaryContainer: Color(0xFFBCEBF0),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1A1C19),
  onBackground: Color(0xFFE2E3DD),
  surface: Color(0xFF1A1C19),
  onSurface: Color(0xFFE2E3DD),
  surfaceVariant: Color(0xFF42493F),
  onSurfaceVariant: Color(0xFFC2C8BC),
  outline: Color(0xFF8C9388),
  onInverseSurface: Color(0xFF1A1C19),
  inverseSurface: Color(0xFFE2E3DD),
  inversePrimary: Color(0xFF006E14),
  shadow: Color(0xFF000000),
  //surfaceTint: Color(0xFF6CDF66),
  surfaceTint: Color(0xFF005225),
  outlineVariant: Color(0xFF42493F),
  scrim: Color(0xFF000000),
);

ThemeData lightTheme = ThemeData(
  fontFamily: 'Poppins',
  useMaterial3: true,
  colorScheme: lightColorScheme,
  scaffoldBackgroundColor: const Color(0xffF7F7F7),
  primaryColor: const Color(0xff1DAE58).withOpacity(0.1),
  // background color
  iconTheme: const IconThemeData(color: Color(0xff464646)),
  cardColor: const Color(0xffEBEBEB),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(color: Color(0xff393939), fontSize: 16, fontWeight: FontWeight.w700),
    headlineSmall: TextStyle(color: Color(0xff1C201E), fontSize: 16, fontWeight: FontWeight.w400),
    bodyLarge: TextStyle(color: Color(0xff2E2E2E), fontSize: 14, fontWeight: FontWeight.w700),
    bodySmall: TextStyle(color: Color(0xff3F3F3F), fontSize: 12, fontWeight: FontWeight.w400),
    titleLarge: TextStyle(color: Color(0xff454545), fontSize: 19, fontWeight: FontWeight.w700),
    titleSmall: TextStyle(color: Color(0xff454545), fontSize: 14, fontWeight: FontWeight.w400),
    titleMedium: TextStyle(color: Color(0xff1C201E), fontSize: 17, fontWeight: FontWeight.w500),
    labelLarge: TextStyle(color: Color(0xff1C201E), fontSize: 19, fontWeight: FontWeight.w600),
    labelMedium: TextStyle(color: Color(0xffF2F6F7), fontSize: 14, fontWeight: FontWeight.w700),
    labelSmall: TextStyle(color: Color(0xff454545), fontSize: 14, fontWeight: FontWeight.w500),
  ),
  primaryColorDark: const Color(0xffF7F7F7),
  //bottom app bar color
  appBarTheme: const AppBarTheme(
    titleTextStyle: TextStyle(color: Color(0xff1C201E), fontWeight: FontWeight.w700, fontSize: 20),
    iconTheme: IconThemeData(color: Color(0xff1C201E), size: 25),
    color: Color(0xffF7F7F7),
  ),
  radioTheme: RadioThemeData(fillColor: MaterialStateProperty.all(const Color(0xff46B946))), //bottom app bar color
);

ThemeData darkTheme = ThemeData(
  fontFamily: 'Poppins',
  useMaterial3: true,
  colorScheme: darkColorScheme,
  primaryColorDark: const Color(0xff17221C),
  //bottom app bar color
  scaffoldBackgroundColor: const Color(0xFF17201B),
  primaryColor: const Color(0xff1DAE58).withOpacity(0.1),
  // background color
  iconTheme: const IconThemeData(color: Color(0xffDADADA)),
  cardColor: const Color(0xff323834),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(color: Color(0xffD4D4D4), fontSize: 16, fontWeight: FontWeight.w700),
    headlineSmall: TextStyle(color: Color(0xffEFEFEF), fontSize: 16, fontWeight: FontWeight.w400),
    bodyLarge: TextStyle(color: Color(0xffF2F6F7), fontSize: 14, fontWeight: FontWeight.w700),
    bodySmall: TextStyle(color: Color(0xffFFFFFF), fontSize: 12, fontWeight: FontWeight.w400),
    titleLarge: TextStyle(color: Color(0xffF2F6F7), fontSize: 19, fontWeight: FontWeight.w700),
    titleSmall: TextStyle(color: Color(0xffE1E1E1), fontSize: 14, fontWeight: FontWeight.w400),
    titleMedium: TextStyle(color: Color(0xffE8E8E8), fontSize: 17, fontWeight: FontWeight.w500),
    labelLarge: TextStyle(color: Color(0xffFFFFFF), fontSize: 19, fontWeight: FontWeight.w600),
    labelMedium: TextStyle(color: Color(0xffF2F6F7), fontSize: 14, fontWeight: FontWeight.w700),
    labelSmall: TextStyle(color: Color(0xffB5B5B5), fontSize: 14, fontWeight: FontWeight.w500),
  ),
  appBarTheme: const AppBarTheme(
    titleTextStyle: TextStyle(color: Color(0xffFFFFFF), fontWeight: FontWeight.w700, fontSize: 20),
    iconTheme: IconThemeData(color: Color(0xffEFEFEF), size: 25),
    color: Color(0xff17221C),
  ),
  radioTheme: RadioThemeData(fillColor: MaterialStateProperty.all(const Color(0xff46B946))),
);
